name: publish

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '20.x'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
      
      - name: Cache TypeScript build info
        uses: actions/cache@v4
        with:
          path: packages/react-contextual-analytics/.tsbuildinfo
          key: ${{ github.runner.os }}-ts-${{ hashFiles('packages/react-contextual-analytics/tsconfig.json') }}
          restore-keys: |
            ${{ github.runner.os }}-ts-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Type check
        working-directory: packages/react-contextual-analytics
        run: pnpm run typecheck
      
      - name: Run tests
        working-directory: packages/react-contextual-analytics
        run: pnpm test
      
      - name: Build package
        working-directory: packages/react-contextual-analytics
        run: pnpm run build
      
      - name: Publish to npm
        working-directory: packages/react-contextual-analytics
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
